modLoader="javafml" 
loaderVersion="*"
license="The Unlicense (Public Domain)"
[[mods]] 
modId="iobtrack"
version="0"

displayName="IOB Tracker"
authors="Kesselot"
description='''A Dragon Tracker for IOB'''

[[dependencies.iobtrack]] 
modId="forge"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.iobtrack]]
modId="minecraft"
mandatory=true
versionRange="1.18.2"
ordering="NONE"
side="BOTH"
[[dependencies.iobtrack]]
modId="minecraft"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"
